defaults: &defaults
  working_directory: ~/repo
  environment:
    PREFIX: /home/circleci/repo/global_node_modules
  docker:
    - image: circleci/node:10.17

version: 2.0
jobs:
  install:
    <<: *defaults
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm rebuild
      - run: npm install -g bslint nyc codecov
      - persist_to_workspace:
          root: .
          paths: .

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: echo 'export PATH=$PREFIX/bin:$PATH' >> $BASH_ENV
      - run:
          name: Tests with coverage
          command: npm run test-ci
      - run:
          name: Submit coverage
          command: codecov

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: echo 'export PATH=$PREFIX/bin:$PATH' >> $BASH_ENV
      - run:
          name: Lint
          command: npm run lint-ci

workflows:
  version: 2
  test_and_lint:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
